@startuml

'!include https://raw.githubusercontent.com/joaohf/OTP-PlantUML/master/OTP_SupervisorTree.iuml
' uncomment the following line and comment the first to use locally
!include OTP_SupervisorTree.iuml

Supervisor(eclero_sup, "eclero_sup", "one_for_one")
GenServer(eclero_detector_server, "eclero_detector_server")
GenServer(eclero_decision_server, "eclero_decision_server")

Rel(eclero_sup, eclero_detector_server)
Rel(eclero_sup, eclero_decision_server)

newpage

node node1 {
  rectangle "eclero" <<erlang node>> as e1
}

node node2 {
  rectangle "eclero" <<erlang node>> as e2
}

node node3 {
  rectangle "eclero" <<erlang node>> as e3
}

node1 -- node2
node1 -- node3

newpage

node devel_host {
  rectangle "ct" <<erlang node>> as h1

  rectangle "eclero1" <<erlang node>> as e1

  rectangle "eclero2" <<erlang node>> as e2

  rectangle "eclero3" <<erlang node>> as e3
}

h1 -d- e1
h1 -d- e2
h1 -d- e3

e1 .d. e2
e1 .d. e3
e3 .l. e2

newpage

title All nodes working

node "eclero 1 <&thumb-up>" <<node>> as n1

node "eclero 2 <&thumb-up>" <<node>> as n2

node "eclero 3 <&thumb-up>" <<node>> as n3

n1 -d- n2 : <&heart>
n1 -d- n3 : <&heart>
n3 -l- n2 : <&heart>

legend
<&heart> good connection
<&thumb-up> node up
end legend

newpage

title Lost one node

node "eclero 1 <&thumb-up>" <<node>> as n1

node "eclero 2 <&thumb-up>" <<node>> as n2

node "eclero 3 <&thumb-down>" <<node>> as n3

n1 -d- n2 : <&heart>
n1 .d. n3 : <&x>
n3 .l. n2 : <&x>

legend
<&x> broken connection
<&thumb-down> node down
end legend

newpage

title Lost two nodes

node "eclero 1 <&thumb-up>" <<node>> as n1

node "eclero 2 <&thumb-down>" <<node>> as n2

node "eclero 3 <&thumb-down>" <<node>> as n3

n1 .d. n2 : <&x>
n1 .d. n3 : <&x>
n3 .l. n2 : <&x>

@enduml
