name: Update this repo's README

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: joaohf/rss-to-readme@v1.2.0
        with:
          feed-url: https://beam-mignon.netlify.app/feed.xml
          readme-section: posts
          max: 100
          pre_template: "| Release Date  |  Link  |\n| :------------- | :------ |"
          template: "| {{ pubDate }} | [{{ title }}]({{ link }}) |"
